--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13
-- Dumped by pg_dump version 15.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: property_logs; Type: TABLE; Schema: public; Owner: scraper_user
--

CREATE TABLE public.property_logs (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(255),
    is_reserved boolean,
    price double precision,
    status smallint,
    property_tick_id bigint NOT NULL,
    CONSTRAINT property_logs_status_check CHECK (((status >= 0) AND (status <= 1)))
);


ALTER TABLE public.property_logs OWNER TO scraper_user;

--
-- Name: property_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: scraper_user
--

ALTER TABLE public.property_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.property_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: property_logs_seq; Type: SEQUENCE; Schema: public; Owner: scraper_user
--

CREATE SEQUENCE public.property_logs_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.property_logs_seq OWNER TO scraper_user;

--
-- Name: property_ticks; Type: TABLE; Schema: public; Owner: scraper_user
--

CREATE TABLE public.property_ticks (
    id bigint NOT NULL,
    origin character varying(255),
    property_key character varying(50),
    url character varying(250),
    is_finished boolean,
    image_url character varying(255),
    CONSTRAINT property_ticks_origin_check CHECK (((origin)::text = 'KV'::text))
);


ALTER TABLE public.property_ticks OWNER TO scraper_user;

--
-- Name: property_ticks_id_seq; Type: SEQUENCE; Schema: public; Owner: scraper_user
--

ALTER TABLE public.property_ticks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.property_ticks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: property_ticks_seq; Type: SEQUENCE; Schema: public; Owner: scraper_user
--

CREATE SEQUENCE public.property_ticks_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.property_ticks_seq OWNER TO scraper_user;

--
-- Data for Name: property_logs; Type: TABLE DATA; Schema: public; Owner: scraper_user
--

COPY public.property_logs (id, created_at, description, is_reserved, price, status, property_tick_id) FROM stdin;
1	2025-07-30 12:41:21.818271	\N	f	0	0	3
2	2025-07-30 12:49:21.839197	\N	f	0	0	3
3	2025-07-30 13:14:04.871157	\N	f	0	0	3
4	2025-07-30 13:51:59.531807	\N	t	474000	0	1
5	2025-07-30 13:56:10.094543	\N	f	490000	0	2
6	2025-07-30 13:59:23.546176	\N	t	458888	0	4
7	2025-07-30 14:03:57.691255	\N	f	449000	0	3
8	2025-08-01 14:01:24.730279	\N	t	474000	\N	1
9	2025-08-01 14:04:48.453876	\N	f	490000	\N	2
10	2025-08-01 14:08:31.907834	\N	t	458888	\N	4
11	2025-08-01 14:12:19.073401	\N	f	449000	\N	3
12	2025-08-02 20:45:03.682061	\N	t	474000	\N	1
13	2025-08-02 20:49:19.140288	\N	f	449000	\N	3
14	2025-08-02 20:53:54.466653	\N	t	458888	\N	4
15	2025-08-02 20:57:57.405504	\N	f	490000	\N	2
16	2025-08-03 10:00:03.023871	\N	t	474000	\N	1
17	2025-08-03 10:03:15.694588	\N	f	449000	\N	3
18	2025-08-03 10:07:00.175102	\N	t	458888	\N	4
19	2025-08-03 10:10:25.01664	\N	f	490000	\N	2
20	2025-08-03 10:30:02.628928	\N	t	474000	\N	1
21	2025-08-03 10:33:55.820698	\N	f	449000	\N	3
22	2025-08-03 10:37:05.916683	\N	t	458888	\N	4
23	2025-08-03 10:40:48.417971	\N	f	490000	\N	2
24	2025-08-03 10:45:07.78415	\N	f	479000	\N	129
25	2025-08-03 10:48:11.773566	\N	f	499000	\N	134
26	2025-08-03 10:52:07.891703	\N	f	395000	\N	135
27	2025-08-03 10:57:01.154766	\N	f	395000	\N	136
28	2025-08-03 11:00:36.677672	\N	f	495000	\N	137
29	2025-08-03 11:03:54.339754	\N	f	315000	\N	138
30	2025-08-03 11:07:16.049381	\N	f	499000	\N	139
31	2025-08-03 11:11:37.521757	\N	f	399900	\N	143
32	2025-08-03 11:16:31.634466	\N	f	480000	\N	144
33	2025-08-03 11:19:42.145762	\N	f	389000	\N	145
34	2025-08-03 11:23:38.412769	\N	t	430000	\N	147
\.


--
-- Data for Name: property_ticks; Type: TABLE DATA; Schema: public; Owner: scraper_user
--

COPY public.property_ticks (id, origin, property_key, url, is_finished, image_url) FROM stdin;
1	KV	3757253	https://www.kv.ee/3757253	f	https://kv.img-bcg.eu/image/object/51/3446/128823446.jpg
3	KV	3768133	https://www.kv.ee/3768133	f	https://kv.img-bcg.eu/image/object/51/0651/129380651.jpg
4	KV	3760216	https://www.kv.ee/3760216	f	https://kv.img-bcg.eu/image/object/51/8920/128978920.jpg
2	KV	3761282	https://www.kv.ee/3761282	f	https://kv.img-bcg.eu/image/object/51/0480/129030480.jpg
129	KV	3728243	https://www.kv.ee/3728243	f	https://kv.img-bcg.eu/image/object/51/8280/128698280.jpg
134	KV	3366043	https://www.kv.ee/3366043	f	https://kv.img-bcg.eu/image/object/51/4939/128984939.jpg
135	KV	3742257	https://www.kv.ee/3742257	f	https://kv.img-bcg.eu/image/object/51/5340/127985340.jpg
136	KV	3749118	https://www.kv.ee/3749118	f	https://kv.img-bcg.eu/image/object/51/4692/128424692.jpg
137	KV	3759565	https://www.kv.ee/3759565	f	https://kv.img-bcg.eu/image/object/51/4810/128944810.jpg
138	KV	3758966	https://www.kv.ee/3758966	f	https://kv.img-bcg.eu/image/object/51/8419/128918419.jpg
139	KV	3731885	https://www.kv.ee/3731885	f	https://kv.img-bcg.eu/image/object/51/6591/127356591.jpg
143	KV	3718973	https://www.kv.ee/3718973	f	https://kv.img-bcg.eu/image/object/51/9489/126589489.jpg
144	KV	3769362	https://www.kv.ee/3769362	f	https://kv.img-bcg.eu/image/object/51/5103/129445103.jpg
145	KV	3762344	https://www.kv.ee/3762344	f	https://kv.img-bcg.eu/image/object/51/2946/129082946.jpg
147	KV	3435141	https://www.kv.ee/3435141	f	https://kv.img-bcg.eu/image/object/51/0448/104190448.jpg
160	KV	3755790	https://www.kv.ee/3755790	f	https://kv.img-bcg.eu/image/object/51/1582/128741582.jpg
161	KV	3722695	https://www.kv.ee/3722695	f	https://kv.img-bcg.eu/image/object/51/8627/126818627.jpg
162	KV	3765201	https://www.kv.ee/3765201	f	https://kv.img-bcg.eu/image/object/51/5388/129225388.jpg
\.


--
-- Name: property_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: scraper_user
--

SELECT pg_catalog.setval('public.property_logs_id_seq', 34, true);


--
-- Name: property_logs_seq; Type: SEQUENCE SET; Schema: public; Owner: scraper_user
--

SELECT pg_catalog.setval('public.property_logs_seq', 1, false);


--
-- Name: property_ticks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: scraper_user
--

SELECT pg_catalog.setval('public.property_ticks_id_seq', 162, true);


--
-- Name: property_ticks_seq; Type: SEQUENCE SET; Schema: public; Owner: scraper_user
--

SELECT pg_catalog.setval('public.property_ticks_seq', 1, false);


--
-- Name: property_logs property_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: scraper_user
--

ALTER TABLE ONLY public.property_logs
    ADD CONSTRAINT property_logs_pkey PRIMARY KEY (id);


--
-- Name: property_ticks property_ticks_pkey; Type: CONSTRAINT; Schema: public; Owner: scraper_user
--

ALTER TABLE ONLY public.property_ticks
    ADD CONSTRAINT property_ticks_pkey PRIMARY KEY (id);


--
-- Name: property_ticks uk48hg315ndwdvfgv2jp5b5mmb1; Type: CONSTRAINT; Schema: public; Owner: scraper_user
--

ALTER TABLE ONLY public.property_ticks
    ADD CONSTRAINT uk48hg315ndwdvfgv2jp5b5mmb1 UNIQUE (origin, property_key);


--
-- Name: property_logs fkn2a3og0jhgrdsvnapo9seq1rr; Type: FK CONSTRAINT; Schema: public; Owner: scraper_user
--

ALTER TABLE ONLY public.property_logs
    ADD CONSTRAINT fkn2a3og0jhgrdsvnapo9seq1rr FOREIGN KEY (property_tick_id) REFERENCES public.property_ticks(id);


--
-- PostgreSQL database dump complete
--

