# --- BUILD STAGE ---
FROM gradle:8.7.0-jdk21 AS build
WORKDIR /app
COPY . .
RUN ./gradlew build -x test

# --- RUNTIME STAGE ---
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/build/libs/*.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
